/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
    ],
    safelist: [
        'w-1/2',
        'w-2/3',
        'w-4/5',
        'text-left',
        'text-center',
        'text-right',
        'bg-tbeige',
        'bg-tpurple',
        'bg-zinc-300',
        'bg-red-700',
        'bg-amber-700',
        'bg-lime-700',
        'bg-indigo-800',
        'text-tbeige',
        'text-tblack',
        'text-tpurple',
        'border-tbeige',
        'border-tblack',
        'border-tpurple',
        'border-tgray',
        'rounded-md',
        'rounded-xl',
        'rounded-full',
        'h-96',
        'h-80',
        'h-72',
        'h-64',
        'h-60',
        'h-52',
        'h-48',
        'h-40',
        'h-32',
        'w-96',
        'w-80',
        'w-72',
        'w-64',
        'w-60',
        'w-52',
        'w-48',
        'w-40',
        'w-32',
    ],
    theme: {
        extend: {
            colors: {
                twhite: '#eeebea',
                tblack: '#000000',
                tgray: '#1b1c26',
                tpurple: '#8d6472',
                tbeige: '#d6c3ba',
            },
            fontFamily: {
                poppins: ['Poppins', 'sans-serif'],
                nightingale: ['DT Nightingale', 'serif'],
            },
        },
    },
    plugins: [],
}

